export type MobileStatsTab = 'tenants' | 'landlords' | 'vendors';

export type AppInstallStatus = 'Installed' | 'Not Installed';

export interface MobileStatsRow {
  id: string;
  name: string;
  email: string;
  company: string;
  tags: string;
  unit: string;
  leases: number;
  gender: string;
  application: AppInstallStatus;
  audience: MobileStatsTab;
}

export const MOBILE_STATS_TABS: { id: MobileStatsTab; label: string }[] = [
  { id: 'tenants', label: 'Tenants' },
  { id: 'landlords', label: 'Landlords' },
  { id: 'vendors', label: 'Vendors' },
];

/** Exactly 10 rows per audience — matches table list cap. */
export const MOBILE_STATS_ROWS: MobileStatsRow[] = [
  // Tenants
  {
    id: '16912',
    name: 'Amal Kumar',
    email: 'amal.kumar@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 0,
    gender: 'Male',
    application: 'Not Installed',
    audience: 'tenants',
  },
  {
    id: '16915',
    name: 'Faisal Nazar',
    email: 'faisal.nazar@example.com',
    company: '—',
    tags: '—',
    unit: '511-PR-4',
    leases: 18,
    gender: 'Male',
    application: 'Installed',
    audience: 'tenants',
  },
  {
    id: '16918',
    name: 'Sara Al Hashimi',
    email: 'sara.hashimi@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 2,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'tenants',
  },
  {
    id: '16921',
    name: 'Omar Farooq',
    email: 'omar.farooq@example.com',
    company: '—',
    tags: '—',
    unit: '102-BL-1',
    leases: 1,
    gender: 'Male',
    application: 'Installed',
    audience: 'tenants',
  },
  {
    id: '16924',
    name: 'Layla Mansoor',
    email: 'layla.mansoor@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 0,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'tenants',
  },
  {
    id: '16927',
    name: 'Hassan Ali',
    email: 'hassan.ali@example.com',
    company: '—',
    tags: '—',
    unit: '220-PR-2',
    leases: 19,
    gender: 'Male',
    application: 'Installed',
    audience: 'tenants',
  },
  {
    id: '16930',
    name: 'Noor Fatima',
    email: 'noor.fatima@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 3,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'tenants',
  },
  {
    id: '16933',
    name: 'Bilal Ahmed',
    email: 'bilal.ahmed@example.com',
    company: '—',
    tags: '—',
    unit: '88-UN-3',
    leases: 1,
    gender: 'Male',
    application: 'Installed',
    audience: 'tenants',
  },
  {
    id: '16936',
    name: 'Maryam Zahra',
    email: 'maryam.zahra@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 0,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'tenants',
  },
  {
    id: '16939',
    name: 'Zain Malik',
    email: 'zain.malik@example.com',
    company: '—',
    tags: '—',
    unit: '15-PR-9',
    leases: 2,
    gender: 'Male',
    application: 'Installed',
    audience: 'tenants',
  },
  // Landlords (10)
  {
    id: '21001',
    name: 'Khalid Al Maktoum',
    email: 'khalid.m@example.com',
    company: 'Maktoum Holdings',
    tags: '—',
    unit: 'N/A',
    leases: 12,
    gender: 'Male',
    application: 'Installed',
    audience: 'landlords',
  },
  {
    id: '21002',
    name: 'Aisha Rahman',
    email: 'aisha.rahman@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 4,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'landlords',
  },
  {
    id: '21003',
    name: 'Yousef Ibrahim',
    email: 'yousef.ibrahim@example.com',
    company: 'Ibrahim Estates',
    tags: 'VIP',
    unit: 'N/A',
    leases: 8,
    gender: 'Male',
    application: 'Installed',
    audience: 'landlords',
  },
  {
    id: '21004',
    name: 'Fatima Noor',
    email: 'fatima.noor@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 2,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'landlords',
  },
  {
    id: '21005',
    name: 'Rashid Al Suwaidi',
    email: 'rashid.s@example.com',
    company: 'Suwaidi Properties',
    tags: '—',
    unit: 'N/A',
    leases: 15,
    gender: 'Male',
    application: 'Installed',
    audience: 'landlords',
  },
  {
    id: '21006',
    name: 'Huda Salim',
    email: 'huda.salim@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 1,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'landlords',
  },
  {
    id: '21007',
    name: 'Tariq Hassan',
    email: 'tariq.hassan@example.com',
    company: 'Hassan Group',
    tags: '—',
    unit: 'N/A',
    leases: 6,
    gender: 'Male',
    application: 'Installed',
    audience: 'landlords',
  },
  {
    id: '21008',
    name: 'Mona Qasimi',
    email: 'mona.qasimi@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 3,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'landlords',
  },
  {
    id: '21009',
    name: 'Samir Khan',
    email: 'samir.khan@example.com',
    company: 'Khan Realty',
    tags: '—',
    unit: 'N/A',
    leases: 9,
    gender: 'Male',
    application: 'Installed',
    audience: 'landlords',
  },
  {
    id: '21010',
    name: 'Leila Haddad',
    email: 'leila.haddad@example.com',
    company: '—',
    tags: '—',
    unit: 'N/A',
    leases: 0,
    gender: 'Female',
    application: 'Not Installed',
    audience: 'landlords',
  },
  // Vendors (10)
  {
    id: '31001',
    name: 'CleanPro Services',
    email: 'ops@cleanpro.example.com',
    company: 'CleanPro LLC',
    tags: 'Cleaning',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Installed',
    audience: 'vendors',
  },
  {
    id: '31002',
    name: 'FixIt Maintenance',
    email: 'desk@fixit.example.com',
    company: 'FixIt Co.',
    tags: 'Maintenance',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Not Installed',
    audience: 'vendors',
  },
  {
    id: '31003',
    name: 'AquaPlumb',
    email: 'support@aquaplumb.example.com',
    company: 'AquaPlumb',
    tags: 'Plumbing',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Installed',
    audience: 'vendors',
  },
  {
    id: '31004',
    name: 'Bright Electric',
    email: 'hello@brightelectric.example.com',
    company: 'Bright Electric',
    tags: 'Electrical',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Not Installed',
    audience: 'vendors',
  },
  {
    id: '31005',
    name: 'GreenLandscaping',
    email: 'team@greenland.example.com',
    company: 'GreenLand LLC',
    tags: '—',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Installed',
    audience: 'vendors',
  },
  {
    id: '31006',
    name: 'SecureGate',
    email: 'ops@securegate.example.com',
    company: 'SecureGate',
    tags: 'Security',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Not Installed',
    audience: 'vendors',
  },
  {
    id: '31007',
    name: 'CoolAir HVAC',
    email: 'service@coolair.example.com',
    company: 'CoolAir',
    tags: 'HVAC',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Installed',
    audience: 'vendors',
  },
  {
    id: '31008',
    name: 'PaintMasters',
    email: 'info@paintmasters.example.com',
    company: 'PaintMasters',
    tags: '—',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Not Installed',
    audience: 'vendors',
  },
  {
    id: '31009',
    name: 'MoveEasy Logistics',
    email: 'dispatch@moveeasy.example.com',
    company: 'MoveEasy',
    tags: 'Logistics',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Installed',
    audience: 'vendors',
  },
  {
    id: '31010',
    name: 'TechFix Gadgets',
    email: 'support@techfix.example.com',
    company: 'TechFix',
    tags: 'IT',
    unit: 'N/A',
    leases: 0,
    gender: '—',
    application: 'Not Installed',
    audience: 'vendors',
  },
];

export function mobileStatsAudienceLabel(tab: MobileStatsTab): string {
  if (tab === 'landlords') {
    return 'landlords';
  }
  if (tab === 'vendors') {
    return 'vendors';
  }
  return 'tenants';
}
