import { Component, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { PageEvent } from '@angular/material/paginator';
import { SharedTableComponent } from '../../shared/components/shared-table/shared-table.component';
import { FilterDrawerComponent } from '../../shared/components/filter-drawer/filter-drawer.component';
import {
  DOWNLOAD_CENTER_JOBS,
  DownloadFileType,
  DownloadJob
} from './download-center.data';

export type { DownloadFileType, DownloadJob } from './download-center.data';

@Component({
  selector: 'app-download-center',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, SharedTableComponent, FilterDrawerComponent],
  templateUrl: './download-center.component.html',
  styleUrls: ['./download-center.component.scss']
})
export class DownloadCenterComponent {
  public searchQuery = '';
  public typeFilter: DownloadFileType = 'All';
  public showTypeDropdown = false;
  public showFilterDrawer = false;
  public pageNo = 0;
  public pageSize = 10;
  public pageSizeOptions = [5, 10, 25, 50, 100];
  public fileTypes: DownloadFileType[] = ['All', 'Excel', 'PDF'];

  public jobs: DownloadJob[] = DOWNLOAD_CENTER_JOBS;

  public tableColumns = [
    { key: 'jobId', label: 'Job Id', visible: true, useTemplate: true },
    { key: 'inspectionId', label: 'Inspection Id', visible: true, useTemplate: true },
    { key: 'type', label: 'Type', visible: true, useTemplate: true },
    { key: 'document', label: 'Document', visible: true },
    { key: 'unit', label: 'Unit', visible: true, useTemplate: true },
    { key: 'generatedBy', label: 'Generated By', visible: true },
    { key: 'requestedAt', label: 'Requested at', visible: true },
    { key: 'action', label: 'Action', visible: true, useTemplate: true }
  ];

  public get visibleColumns() {
    return this.tableColumns.filter((col) => col.visible);
  }

  public get filteredJobs(): DownloadJob[] {
    const query = this.searchQuery.trim().toLowerCase();
    return this.jobs.filter((job) => {
      const typeMatch = this.typeFilter === 'All' || job.type === this.typeFilter;
      const searchMatch =
        !query ||
        job.document.toLowerCase().includes(query) ||
        job.jobId.toLowerCase().includes(query);
      return typeMatch && searchMatch;
    });
  }

  public get totalRecords(): number {
    return this.filteredJobs.length;
  }

  public get pagedJobs(): DownloadJob[] {
    const start = this.pageNo * this.pageSize;
    return this.filteredJobs.slice(start, start + this.pageSize);
  }

  public setTypeFilter(type: DownloadFileType): void {
    this.typeFilter = type;
    this.showTypeDropdown = false;
    this.pageNo = 0;
  }

  public onSearch(): void {
    this.pageNo = 0;
  }

  public toggleDrawer(show: boolean): void {
    this.showFilterDrawer = show;
  }

  public toggleTypeDropdown(event: Event): void {
    event.stopPropagation();
    this.showTypeDropdown = !this.showTypeDropdown;
  }

  public dash(value: string | null): string {
    return value || '—';
  }

  public deleteJob(jobId: string): void {
    const index = this.jobs.findIndex((job) => job.jobId === jobId);
    if (index >= 0) {
      this.jobs.splice(index, 1);
    }
    const lastPage = Math.max(0, Math.ceil(this.filteredJobs.length / this.pageSize) - 1);
    if (this.pageNo > lastPage) {
      this.pageNo = lastPage;
    }
  }

  public onSharedTablePageChange(event: PageEvent): void {
    this.pageNo = event.pageIndex;
    this.pageSize = event.pageSize;
  }

  @HostListener('document:click')
  public onDocumentClick(): void {
    this.showTypeDropdown = false;
  }
}
