export type UserKind = 'user' | 'admin' | 'technician';
export type UserStatus = 'active' | 'blocked';

export interface SettingsUserRow {
  id: number;
  kind: UserKind;
  name: string;
  email: string;
  username: string;
  phone: string;
  role: string;
  referenceNo: string;
  lastLogin: string;
  units: number;
  status: UserStatus;
  initials: string;
  avatarColor: string;
}

export const USER_NOTIFICATION_OPTIONS: string[] = [
  'Agent Assigned to Unit',
  'Assigned Ticket Email',
  'Cheque Bounced Notification',
  'Contract Ending',
  'Daily summary',
  'Delayed Inspection Reminder Email',
  'Delayed Rent by Tenant',
  'Document Expiry Email',
  'Event Join',
  'Export Completed',
  'Hold Payment',
  'Inspection Report Email',
  'Landlord have signed Contract',
  'Lease Ending Reminder Email',
  'Lease Start',
  'Manager Lease Completed',
  'Manager Lease End Email',
  'Manager New Ticket Email',
  'Manager Work Order Reminder email',
  'New Landlord Added Email',
  'New Lead Added Email',
  'New Legal Case Created',
  'New Legal Case Escalated',
  'New Property Added Email',
  'New Reservation',
  'New Tenant Added Email',
  'New Unit Added Email',
  'New approval request',
  'New inspection assigned email',
  'New system feedback created',
  'New task reminder email',
  'PO Invoice Reminder',
  'Quotation Submission',
  'Received new Reservation',
  'Reminder Notification email',
  'Request Approved',
  'System feedback closed',
  'Tenant has a new feedback',
  'Ticket Note Added Email',
  "Vendor's quotation rejection",
  'Upcoming Inspection Reminder Email',
  'Upcoming task reminder email',
  'Welcome User Email',
  'Work Order Due Reminder',
  'Work Order Emails',
  'Work Order Note Added Email',
];

export const MOCK_SETTINGS_USERS: SettingsUserRow[] = [
  {
    id: 1,
    kind: 'user',
    name: 'Ahmed Hassan',
    email: 'ahmed.hassan@orville.ae',
    username: 'ahmed.h',
    phone: '+971501234567',
    role: 'Collector',
    referenceNo: '',
    lastLogin: '12-03-2026',
    units: 14,
    status: 'active',
    initials: 'AH',
    avatarColor: '#D08A28',
  },
  {
    id: 2,
    kind: 'user',
    name: 'Sara Al Maktoum',
    email: 'sara.m@orville.ae',
    username: 'sara.m',
    phone: '+971509876543',
    role: 'Inspector',
    referenceNo: 'REF-102',
    lastLogin: '10-03-2026',
    units: 8,
    status: 'active',
    initials: 'SA',
    avatarColor: '#BD9759',
  },
  {
    id: 3,
    kind: 'user',
    name: 'John Miller',
    email: 'john.miller@orville.ae',
    username: 'jmiller',
    phone: '+971551112233',
    role: 'Manager',
    referenceNo: '',
    lastLogin: '08-03-2026',
    units: 32,
    status: 'active',
    initials: 'JM',
    avatarColor: '#8B6B4A',
  },
  {
    id: 4,
    kind: 'user',
    name: 'Fatima Noor',
    email: 'fatima.n@orville.ae',
    username: 'fatima.n',
    phone: '+971524445566',
    role: 'Accountant',
    referenceNo: '',
    lastLogin: '01-02-2026',
    units: 0,
    status: 'blocked',
    initials: 'FN',
    avatarColor: '#3E6FA8',
  },
  {
    id: 5,
    kind: 'admin',
    name: 'Hafeez Hafeez',
    email: 'hafeez@orville.ae',
    username: 'hafeez',
    phone: '+971500000001',
    role: 'Manager',
    referenceNo: 'ADM-01',
    lastLogin: '24-03-2026',
    units: 120,
    status: 'active',
    initials: 'HH',
    avatarColor: '#26264F',
  },
  {
    id: 6,
    kind: 'admin',
    name: 'Layla Ibrahim',
    email: 'layla@orville.ae',
    username: 'layla.i',
    phone: '+971500000002',
    role: 'Admin',
    referenceNo: 'ADM-02',
    lastLogin: '20-03-2026',
    units: 45,
    status: 'active',
    initials: 'LI',
    avatarColor: '#27865B',
  },
  {
    id: 7,
    kind: 'technician',
    name: 'Omar Tech',
    email: 'omar.tech@orville.ae',
    username: 'omar.t',
    phone: '+971507778899',
    role: 'Support Technician',
    referenceNo: '',
    lastLogin: '15-03-2026',
    units: 0,
    status: 'active',
    initials: 'OT',
    avatarColor: '#6B6B7D',
  },
];
